# ==================================================
# NOMBRE MICROSERVICIO
# ==================================================
spring.application.name=riesgo-ms

# ==================================================
# PUERTO
# ==================================================
server.port=8080

# ==================================================
# MYSQL
# ==================================================
spring.datasource.url=jdbc:mysql://localhost:3306/riesgo_db

spring.datasource.username=root

spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==================================================
# JPA
# ==================================================

# CREA TABLAS AUTOMÁTICAS
spring.jpa.hibernate.ddl-auto=update

# MUESTRA SQL EN CONSOLA
spring.jpa.show-sql=true

# FORMATEA SQL
spring.jpa.properties.hibernate.format_sql=true