server:
  port: 8085

spring:
  application:
    name: riesgo-ms
  security:
    user:
      name: admin
      password: comex123
  datasource:
    url: jdbc:mysql://localhost:3306/riesgo_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    repair-at-start: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:comex123@localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs