spring.application.name=gestion-carga-ms
server.port=8081

# Configuración Base de Datos (Laragon / MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/carga_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway Migraciones
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# URL externa para el Cliente Feign
services.clasificacion.url=http://localhost:8082

# Logs para Trazabilidad (Exigido en rúbrica)
logging.level.org.springframework.web=INFO
logging.level.com.comex.gestioncarga=DEBUG