server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    user:
      name: admin
      password: comex123
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: carga-ms
          uri: lb://carga-ms
          predicates:
            - Path=/api/v1/cargas/**
        - id: clasificacion-ms
          uri: lb://clasificacion-ms
          predicates:
            - Path=/api/v1/clasificaciones/**
        - id: pagos-ms
          uri: lb://pagos-ms
          predicates:
            - Path=/api/v1/pagos/**
        - id: documentos-ms
          uri: lb://documentos-ms
          predicates:
            - Path=/api/v1/documentos/**
        - id: riesgo-ms
          uri: lb://riesgo-ms
          predicates:
            - Path=/api/v1/riesgos/**
        - id: banco-ms
          uri: lb://banco-ms
          predicates:
            - Path=/api/v1/banco/**
        - id: notificacion-ms
          uri: lb://notificacion-ms
          predicates:
            - Path=/api/v1/notificaciones/**
        - id: carga-swagger
          uri: lb://carga-ms
          predicates:
            - Path=/carga-ms/v3/api-docs
          filters:
            - SetPath=/v3/api-docs  # 👈 Le quita el prefijo antes de enviarlo al MS interno

        - id: banco-swagger
          uri: lb://banco-ms
          predicates:
            - Path=/banco-ms/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: riesgo-swagger
          uri: lb://riesgo-ms
          predicates:
            - Path=/riesgo-ms/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: documentos-swagger
          uri: lb://documentos-ms
          predicates:
            - Path=/documentos-ms/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://admin:comex123@eureka-server:8761/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: 🏦 Microservicio de Bancos
        url: /banco-ms/v3/api-docs
      - name: 📦 Microservicio de Carga
        url: /carga-ms/v3/api-docs
      - name: 🛡️ Microservicio de Riesgo
        url: /riesgo-ms/v3/api-docs
      - name: 📑 Microservicio de Documentos
        url: /documentos-ms/v3/api-docs
    operationsSorter: method