server:
  port: 8081

spring:
  application:
    name: carga-ms
  security:
    user:
      name: admin
      password: comex123
  datasource:
    url: jdbc:mysql://mysql-comex:3306/carga_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    repair-at-start: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:comex123@eureka-server:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  server:
    url: http://localhost:8080