server:
  port: 8091

spring:
  application:
    name: banco-ms
  security:
    user:
      name: admin
      password: comex123

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:comex123@eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

client:
  # ESTO HACE QUE EL BANCO INTENTE REGISTRARSE MUCHAS VECES HASTA QUE EUREKA DESPIERTE
  initial-instance-info-replication-interval-seconds: 5
  registry-fetch-interval-seconds: 5

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  server:
    url: http://localhost:8080