spring.application.name=notificacion-ms

server.port=8086

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/notificacion_db
spring.datasource.username=root
spring.datasource.password=TU_PASSWORD

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DRIVER MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ASYNC
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5

# FEIGN
spring.cloud.openfeign.enabled=true