server:
  port: 8761

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: comex123

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:comex123@eureka-server:8761/eureka/