server:
  port: 8082

spring:
  application:
    name: clasificacion-ms
  security:
    user:
      name: admin
      password: comex123
  datasource:
    url: jdbc:mysql://mysql-comex:3306/clasificacion_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://admin:comex123@eureka-server:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs